workspace: "d-ng-nguy-n"

directories:
  raw_dir: "experiments/static/raw"
  merge_dir: "experiments/static/merged"
  output_dir: "assets/static"

hyperparameters:
  - preload_fraction
  - preload-fraction

metric_keys:
  - "cdlib_modularity"
  - "customize_q0_modularity"
  - "nmi"
  - "num_communities"
  - "runtime"

use_batch_ranges: false

projects:
  - graph-community-detection-static-collegemsg
  - graph-community-detection-static-email-enron-large
  - graph-community-detection-static-ia-frwikinews-user-edits
  - graph-community-detection-static-soc-sign-bitcoin-otc
  - graph-community-detection-static-soc-sign-bitcoin-alpha
  - graph-community-detection-static-ca-condmat
  - graph-community-detection-static-sx_mathoverflow
  - graph-community-detection-static-edit-enwikibooks
  - graph-community-detection-static-lfr_large_community_size
  - graph-community-detection-static-bio-wormnet-v3
  - graph-community-detection-static-lfr_small_community_size
  - graph-community-detection-static-ca-hepph
  - graph-community-detection-static-ca-astroph
  - graph-community-detection-static-scc_infect_dublin
  - graph-community-detection-static-scc_infect_hyper
  - graph-community-detection-static-scc_tweeter_copen
  - graph-community-detection-static-scc_retweet
  - graph-community-detection-static-sx_askubuntu
  - graph-community-detection-static-synthetic-n10000-mu0-1-on200500-om2-4-k50-100-c50-200
  - graph-community-detection-static-synthetic-n10000-mu0-2-on200500-om2-4-k50-100-c50-200
  - graph-community-detection-static-synthetic-n10000-mu0-3-on200500-om2-4-k50-100-c50-200
  - graph-community-detection-static-synthetic-n10000-mu0-4-on200500-om2-4-k50-100-c50-200
  - graph-community-detection-static-synthetic-n10000-mu0-5-on200500-om2-4-k50-100-c50-200
  - graph-community-detection-static-synthetic-n10000-mu0-25-on200500-om2-4-k50-100-c50-200

plotter:
  common_plotter_settings:
    synthetic_datasets: &static_synthetic_datasets
      - graph-community-detection-static-synthetic-n10000-mu0-1-on200500-om2-4-k50-100-c50-200
      - graph-community-detection-static-synthetic-n10000-mu0-2-on200500-om2-4-k50-100-c50-200
      - graph-community-detection-static-synthetic-n10000-mu0-3-on200500-om2-4-k50-100-c50-200
      - graph-community-detection-static-synthetic-n10000-mu0-4-on200500-om2-4-k50-100-c50-200
      - graph-community-detection-static-synthetic-n10000-mu0-5-on200500-om2-4-k50-100-c50-200
      # - graph-community-detection-static-synthetic-n10000-mu0-25-on200500-om2-4-k50-100-c50-200
    real_world_datasets: &static_real_world_datasets
      - graph-community-detection-static-bio-wormnet-v3
      - graph-community-detection-static-ca-condmat
      - graph-community-detection-static-ca-hepph
      - graph-community-detection-static-ca-astroph
      - graph-community-detection-static-collegemsg
      - graph-community-detection-static-edit-enwikibooks
      - graph-community-detection-static-ia-frwikinews-user-edits
      - graph-community-detection-static-soc-sign-bitcoin-alpha
      - graph-community-detection-static-soc-sign-bitcoin-otc
      - graph-community-detection-static-email-enron-large
      # - graph-community-detection-static-sx_askubuntu
      # - graph-community-detection-static-scc_infect_dublin
      # - graph-community-detection-static-scc_infect_hyper
      # - graph-community-detection-static-scc_tweeter_copen
      # - graph-community-detection-static-scc_retweet
      # - graph-community-detection-static-sx_mathoverflow
    projects_name_mapping:
      graph-community-detection-static-bio-wormnet-v3: "Bio-WormNet-v3"
      graph-community-detection-static-ca-condmat: "CA-CondMat"
      graph-community-detection-static-ca-hepph: "CA-Hepph"
      graph-community-detection-static-ca-astroph: "CA-AstroPh"
      graph-community-detection-static-collegemsg: "CollegeMsg"
      graph-community-detection-static-edit-enwikibooks: "Edit-Enwikibooks"
      graph-community-detection-static-email-enron-large: "Email-Enron-Large"
      graph-community-detection-static-ia-frwikinews-user-edits: "IA-FrWikiNews-User-Edits"
      graph-community-detection-static-lfr_large_community_size: "LFR-Large-Community-Size"
      graph-community-detection-static-lfr_small_community_size: "LFR-Small-Community-Size"
      graph-community-detection-static-scc_infect_dublin: "SCC-Infect-Dublin"
      graph-community-detection-static-scc_infect_hyper: "SCC-Infect-Hyper"
      graph-community-detection-static-scc_retweet: "SCC-Retweet"
      graph-community-detection-static-scc_tweeter_copen: "SCC-Tweeter-Copen"
      graph-community-detection-static-soc-sign-bitcoin-alpha: "Soc-Sign-Bitcoin-Alpha"
      graph-community-detection-static-soc-sign-bitcoin-otc: "Soc-Sign-Bitcoin-OTC"
      graph-community-detection-static-sx_askubuntu: "SX-AskUbuntu"
      graph-community-detection-static-sx_mathoverflow: "SX-MathOverflow"
      graph-community-detection-static-synthetic-n10000-mu0-1-on200500-om2-4-k50-100-c50-200: "mu=0.1"
      graph-community-detection-static-synthetic-n10000-mu0-2-on200500-om2-4-k50-100-c50-200: "mu=0.2"
      graph-community-detection-static-synthetic-n10000-mu0-3-on200500-om2-4-k50-100-c50-200: "mu=0.3"
      graph-community-detection-static-synthetic-n10000-mu0-4-on200500-om2-4-k50-100-c50-200: "mu=0.4"
      graph-community-detection-static-synthetic-n10000-mu0-5-on200500-om2-4-k50-100-c50-200: "mu=0.5"
      graph-community-detection-static-synthetic-n10000-mu0-25-on200500-om2-4-k50-100-c50-200: "mu=0.25"
    metric_name_mapping:
      nmi: "ONMI"
      cdlib_modularity: "Modularity (CDLib)"
      # customize_q0_modularity: "Overlap Modularity"
      customize_q0_modularity: " "
      num_communities: "Number of Communities"
      runtime: "Execution Time (s)"
    selected_algorithms:
      - coach
      - tiles
      - core_expansion
      - graph_entropy
      # - overlapping_rwgp_df
      - vast-pmo
    methods_name:
      coach: CoAcH
      core_expansion: Core Expansion
      graph_entropy: Graph Entropy
      umstmo: UMSTMO
      overlapping_rwgp_df: RWGP-DFL-Overlap
      tiles: Tiles
      slpa: SLPA
      vast-pmo: Structured-PMO
    colors:
      vast-pmo: "#E74C3C"
      # overlapping_rwgp_df: "#E74C3C"
      coach: "#1B4F72"
      core_expansion: "#E09F3E"
      graph_entropy: "#2E8B57"
      slpa: "#8E44AD"
      umstmo: "#C0392B"
      tiles: "#17A2B8"
    orders:
      - vast-pmo
      # - overlapping_rwgp_df
      - coach
      - core_expansion
      - graph_entropy
      # - tiles
      # - slpa
    markers:
      vast5-pmo: "v"
      coach: "o"
      core_expansion: "s"
      graph_entropy: "D"
      umstmo: "^"
      # overlapping_rwgp_df: "v"
      slpa: "P"
      tiles: "X"
  metric_modes:
    nmi: ["bar", "box", "line"]
    cdlib_modularity: ["box", "bar", "line"]
    customize_q0_modularity: ["box", "bar", "line"]
    num_communities: ["line"]
    runtime: ["line"]
  grouped_plotter:
    synthetic_datasets: *static_synthetic_datasets
    real_world_datasets: *static_real_world_datasets
    group_by:
      - real_world_datasets
      - synthetic_datasets
    subplots_layout:
      real_world_datasets: [2, 5]
      synthetic_datasets: [1, 5]
